version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/python:3.9.9"
    steps:
      - checkout
      - run:
          name: Try to build
          command: |
            pip3 install -r requirements.txt
            python3 Main.py
  test:
    docker:
      - image: "circleci/python:3.9.9"
    steps:
      - checkout
      - run:
          name: Tests
          command: |
            pip3 install -r requirements.txt
            python3 Test.py

workflows:
  build:
    jobs:
      - build
      - test:
        requires:
          -build
